tap "homebrew/cask"

# App
brew "tmux"
brew "tig"
brew "tree"
brew "wget"
brew "mycli"
brew "vim"
brew "fish"
brew "ffmpeg"

cask "iterm2"
cask "macdown"
cask "visual-studio-code"
cask "sequel-ace"
cask "insomnia"
cask "iina"
cask "the-unarchiver"
cask "charles"
# cask "xquartz"

# Dev
tap "adoptopenjdk/openjdk"
cask "adoptopenjdk11"
cask "virtualbox"
cask "vagrant"
cask "docker"
brew "nginx"
brew "mysql"
brew "redis"

# Spakce
cask "mqttx"
cask "adrive"
cask "wechat"
cask "tencent-meeting"
cask "todesk"
cask "google-chrome"
