tap "homebrew/cask"
tap "homebrew/services"

# App
brew "tmux"
brew "tig"
brew "tree"
brew "wget"
brew "vim"

cask "iterm2"
cask "macdown"
cask "visual-studio-code"
cask "sequel-ace"
cask "insomnia"
cask "iina"
cask "the-unarchiver"
cask "charles"
cask "xquartz"

# Dev
tap "adoptopenjdk/openjdk"
cask "virtualbox"
cask "vagrant"
cask "docker"
cask "adoptopenjdk11"
brew "mysql"
brew "postgresql@14"
brew "redis"
brew "node@18"
brew "rbenv"

# Spakce
cask "mqttx"
cask "adrive"
cask "wechat"
cask "tencent-meeting"
cask "todesk"
cask "google-chrome"
